export * from './trendingMovieData';
export * from './trendingTvData';
export * from './trendingPersonData';
export * from './detailedMovie';
export * from './movieCredits';
export * from './movieVideos';
export * from './externalLinks'
export * from './detailedTv';
export * from './ImovieRecommendations';
export * from './ITVRecommendations'