export * from './trendingMovieData';
export * from './trendingTvData';
export * from './trendingPersonData';
export * from './detailedMovie';
export * from './movieCredits';
export * from './movieVideos';
export * from './externalLinks'
export * from './detailedTv';
export * from './ImovieRecommendations';
export * from './ITVRecommendations';
export * from './personInformation';
export * from './personMovieCredits';
export * from './personTvCredits';
export * from './personCombinedCredits';
export * from './mediaGenres';