version: '3'

services:
  db:
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    container_name: screenIdDB
    volumes:
      - ./postgres:/var/lib/postgresql/data